# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59db3f9f7771fc8d81bb176d03dcc69beb2fa670a3c535854f5bae61bb8e3798533beedcd45ab6715453bd6322161a6f53de492f6bbfa92b59609d5cfc25cac2

test:
  secret_key_base: dec139e87dcc0b582739125fb79b76832544933a5420a27f9fba99e8e9f184180f1a72b7b082cdf864900873885e7724988ff5b77664bf4ba3efb033574deafc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
